// Code generated by MockGen. DO NOT EDIT.
// Source: job_config.go
//
// Generated by this command:
//
//	mockgen -source=job_config.go -destination=mock/job_config.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	entity "github.com/goda6565/ai-consultant/backend/internal/domain/job_config/entity"
	value "github.com/goda6565/ai-consultant/backend/internal/domain/shared/value"
	gomock "go.uber.org/mock/gomock"
)

// MockJobConfigRepository is a mock of JobConfigRepository interface.
type MockJobConfigRepository struct {
	ctrl     *gomock.Controller
	recorder *MockJobConfigRepositoryMockRecorder
	isgomock struct{}
}

// MockJobConfigRepositoryMockRecorder is the mock recorder for MockJobConfigRepository.
type MockJobConfigRepositoryMockRecorder struct {
	mock *MockJobConfigRepository
}

// NewMockJobConfigRepository creates a new mock instance.
func NewMockJobConfigRepository(ctrl *gomock.Controller) *MockJobConfigRepository {
	mock := &MockJobConfigRepository{ctrl: ctrl}
	mock.recorder = &MockJobConfigRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockJobConfigRepository) EXPECT() *MockJobConfigRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockJobConfigRepository) Create(ctx context.Context, jobConfig *entity.JobConfig) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, jobConfig)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockJobConfigRepositoryMockRecorder) Create(ctx, jobConfig any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockJobConfigRepository)(nil).Create), ctx, jobConfig)
}

// DeleteByProblemID mocks base method.
func (m *MockJobConfigRepository) DeleteByProblemID(ctx context.Context, problemID value.ID) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByProblemID", ctx, problemID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteByProblemID indicates an expected call of DeleteByProblemID.
func (mr *MockJobConfigRepositoryMockRecorder) DeleteByProblemID(ctx, problemID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByProblemID", reflect.TypeOf((*MockJobConfigRepository)(nil).DeleteByProblemID), ctx, problemID)
}

// FindByProblemID mocks base method.
func (m *MockJobConfigRepository) FindByProblemID(ctx context.Context, problemID value.ID) (*entity.JobConfig, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByProblemID", ctx, problemID)
	ret0, _ := ret[0].(*entity.JobConfig)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByProblemID indicates an expected call of FindByProblemID.
func (mr *MockJobConfigRepositoryMockRecorder) FindByProblemID(ctx, problemID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByProblemID", reflect.TypeOf((*MockJobConfigRepository)(nil).FindByProblemID), ctx, problemID)
}

// Update mocks base method.
func (m *MockJobConfigRepository) Update(ctx context.Context, jobConfig *entity.JobConfig) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, jobConfig)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockJobConfigRepositoryMockRecorder) Update(ctx, jobConfig any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockJobConfigRepository)(nil).Update), ctx, jobConfig)
}
