substitutions:
  _REGION: 'asia-northeast1'
  _ENV: 'staging'
  _APP_NAME: 'backend-proposal-job'
  _CONTAINER: '${_REGION}-docker.pkg.dev/${PROJECT_ID}/shared-ai-consultant-artifact-registry/${_APP_NAME}/${_ENV}:${SHORT_SHA}'

options:
  automapSubstitutions: true
  logging: CLOUD_LOGGING_ONLY
  env:
    - DOCKER_BUILDKIT=1

steps:
- name: 'gcr.io/kaniko-project/executor:latest'
  args:
  - --destination=${_CONTAINER}
  - --cache=true
  - --cache-ttl=24h
  - --context=backend
  - --dockerfile=Dockerfile.proposal-job
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
    - run
    - jobs
    - update
    - staging-ai-consultant-backend-proposal-job
    - '--image=${_CONTAINER}'
    - '--region=${_REGION}'