// Code generated by MockGen. DO NOT EDIT.
// Source: hearing_map.go
//
// Generated by this command:
//
//	mockgen -source=hearing_map.go -destination=mock/hearing_map.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	entity "github.com/goda6565/ai-consultant/backend/internal/domain/hearing_map/entity"
	value "github.com/goda6565/ai-consultant/backend/internal/domain/shared/value"
	gomock "go.uber.org/mock/gomock"
)

// MockHearingMapRepository is a mock of HearingMapRepository interface.
type MockHearingMapRepository struct {
	ctrl     *gomock.Controller
	recorder *MockHearingMapRepositoryMockRecorder
	isgomock struct{}
}

// MockHearingMapRepositoryMockRecorder is the mock recorder for MockHearingMapRepository.
type MockHearingMapRepositoryMockRecorder struct {
	mock *MockHearingMapRepository
}

// NewMockHearingMapRepository creates a new mock instance.
func NewMockHearingMapRepository(ctrl *gomock.Controller) *MockHearingMapRepository {
	mock := &MockHearingMapRepository{ctrl: ctrl}
	mock.recorder = &MockHearingMapRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHearingMapRepository) EXPECT() *MockHearingMapRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockHearingMapRepository) Create(ctx context.Context, hearingMap *entity.HearingMap) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, hearingMap)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockHearingMapRepositoryMockRecorder) Create(ctx, hearingMap any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockHearingMapRepository)(nil).Create), ctx, hearingMap)
}

// DeleteByHearingID mocks base method.
func (m *MockHearingMapRepository) DeleteByHearingID(ctx context.Context, hearingID value.ID) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByHearingID", ctx, hearingID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteByHearingID indicates an expected call of DeleteByHearingID.
func (mr *MockHearingMapRepositoryMockRecorder) DeleteByHearingID(ctx, hearingID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByHearingID", reflect.TypeOf((*MockHearingMapRepository)(nil).DeleteByHearingID), ctx, hearingID)
}

// FindByHearingID mocks base method.
func (m *MockHearingMapRepository) FindByHearingID(ctx context.Context, hearingID value.ID) (*entity.HearingMap, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByHearingID", ctx, hearingID)
	ret0, _ := ret[0].(*entity.HearingMap)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByHearingID indicates an expected call of FindByHearingID.
func (mr *MockHearingMapRepositoryMockRecorder) FindByHearingID(ctx, hearingID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByHearingID", reflect.TypeOf((*MockHearingMapRepository)(nil).FindByHearingID), ctx, hearingID)
}
