/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * AI-Consultant Admin API
 * AI-Consultant Admin API
 * OpenAPI spec version: 1.0.0
 */
import type { ActionType } from "./actionType";

export interface Action {
  id: string;
  problemId: string;
  actionType: ActionType;
  input: string;
  output: string;
  createdAt: string;
}
