/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * AI-Consultant Admin API
 * AI-Consultant Admin API
 * OpenAPI spec version: 1.0.0
 */
import type { DocumentType } from "./documentType";

export type CreateDocumentBody = {
  title: string;
  documentType: DocumentType;
  /** File data in base64 */
  data: string;
};
