/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * AI-Consultant Admin API
 * AI-Consultant Admin API
 * OpenAPI spec version: 1.0.0
 */

import type { DocumentStatus } from "./documentStatus";
import type { DocumentType } from "./documentType";

export interface Document {
  id: string;
  title: string;
  documentType: DocumentType;
  bucketName: string;
  objectName: string;
  documentStatus: DocumentStatus;
  retryCount: number;
  createdAt: string;
  updatedAt: string;
}
