/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * AI-Consultant Admin API
 * AI-Consultant Admin API
 * OpenAPI spec version: 1.0.0
 */

import type { ActionType } from "./actionType";
import type { EventType } from "./eventType";

export interface Event {
  id: string;
  eventType: EventType;
  actionType: ActionType;
  message: string;
}
