/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * AI-Consultant Admin API
 * AI-Consultant Admin API
 * OpenAPI spec version: 1.0.0
 */
import type { Document } from "./document";

/**
 * Get document response
 */
export type GetDocumentSuccessResponse = Document;
