/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * AI-Consultant Admin API
 * AI-Consultant Admin API
 * OpenAPI spec version: 1.0.0
 */

export type HearingMessageRole =
  (typeof HearingMessageRole)[keyof typeof HearingMessageRole];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const HearingMessageRole = {
  user: "user",
  assistant: "assistant",
} as const;
