/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * AI-Consultant Admin API
 * AI-Consultant Admin API
 * OpenAPI spec version: 1.0.0
 */
import type { HearingMessageRole } from "./hearingMessageRole";

export interface HearingMessage {
  id: string;
  hearingId: string;
  problemFieldId: string;
  role: HearingMessageRole;
  message: string;
  createdAt: string;
}
