/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * AI-Consultant Admin API
 * AI-Consultant Admin API
 * OpenAPI spec version: 1.0.0
 */
import type { Event } from "./event";

export type ListEventsSuccessResponse = {
  events: Event[];
};
