/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * AI-Consultant Admin API
 * AI-Consultant Admin API
 * OpenAPI spec version: 1.0.0
 */
import type { ProblemStatus } from "./problemStatus";

export interface Problem {
  id: string;
  title: string;
  description: string;
  status: ProblemStatus;
  createdAt: string;
}
