/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * AI-Consultant Admin API
 * AI-Consultant Admin API
 * OpenAPI spec version: 1.0.0
 */

export type ProblemStatus = (typeof ProblemStatus)[keyof typeof ProblemStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ProblemStatus = {
  pending: "pending",
  hearing: "hearing",
  processing: "processing",
  done: "done",
  failed: "failed",
} as const;
