/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * AI-Consultant Agent API
 * AI-Consultant Agent API
 * OpenAPI spec version: 1.0.0
 */

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ErrorCode = {
  NUMBER_400: 400,
  NUMBER_401: 401,
  NUMBER_403: 403,
  NUMBER_404: 404,
  NUMBER_409: 409,
  NUMBER_500: 500,
} as const;
