/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * AI-Consultant Agent API
 * AI-Consultant Agent API
 * OpenAPI spec version: 1.0.0
 */

export type ExecuteHearingRequestBody = {
  /**
   * User's message to the AI consultant
   * @nullable
   */
  user_message?: string | null;
};
