/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * AI-Consultant Agent API
 * AI-Consultant Agent API
 * OpenAPI spec version: 1.0.0
 */

export type ExecuteHearingSuccessResponse = {
  /** AI consultant's response message */
  assistant_message: string;
  /** Whether the hearing is completed */
  is_completed: boolean;
};
