/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * AI-Consultant Admin API
 * AI-Consultant Admin API
 * OpenAPI spec version: 1.0.0
 */

import type { Key, SWRConfiguration } from "swr";
import useSwr from "swr";
import { adminApiClient } from "../../client";
import type { ErrorResponse, ListActionsSuccessResponse } from ".././model";

/**
 * @summary List actions by problem id
 */
export const listActions = (problemId: string) => {
  return adminApiClient<ListActionsSuccessResponse>({
    url: `/api/actions/${problemId}`,
    method: "GET",
  });
};

export const getListActionsKey = (problemId: string) =>
  [`/api/actions/${problemId}`] as const;

export type ListActionsQueryResult = NonNullable<
  Awaited<ReturnType<typeof listActions>>
>;
export type ListActionsQueryError =
  | ErrorResponse
  | ErrorResponse
  | ErrorResponse
  | ErrorResponse
  | ErrorResponse;

/**
 * @summary List actions by problem id
 */
export const useListActions = <
  TError =
    | ErrorResponse
    | ErrorResponse
    | ErrorResponse
    | ErrorResponse
    | ErrorResponse,
>(
  problemId: string,
  options?: {
    swr?: SWRConfiguration<Awaited<ReturnType<typeof listActions>>, TError> & {
      swrKey?: Key;
      enabled?: boolean;
    };
  },
) => {
  const { swr: swrOptions } = options ?? {};

  const isEnabled = swrOptions?.enabled !== false && !!problemId;
  const swrKey =
    swrOptions?.swrKey ??
    (() => (isEnabled ? getListActionsKey(problemId) : null));
  const swrFn = () => listActions(problemId);

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(
    swrKey,
    swrFn,
    swrOptions,
  );

  return {
    swrKey,
    ...query,
  };
};
