/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * AI-Consultant Admin API
 * AI-Consultant Admin API
 * OpenAPI spec version: 1.0.0
 */

import type { Key, SWRConfiguration } from "swr";
import useSwr from "swr";
import { adminApiClient } from "../../client";
import type { ErrorResponse, GetHearingSuccessResponse } from ".././model";

/**
 * @summary Get a hearing by problem id
 */
export const getHearing = (problemId: string) => {
  return adminApiClient<GetHearingSuccessResponse>({
    url: `/api/hearings/${problemId}`,
    method: "GET",
  });
};

export const getGetHearingKey = (problemId: string) =>
  [`/api/hearings/${problemId}`] as const;

export type GetHearingQueryResult = NonNullable<
  Awaited<ReturnType<typeof getHearing>>
>;
export type GetHearingQueryError =
  | ErrorResponse
  | ErrorResponse
  | ErrorResponse
  | ErrorResponse
  | ErrorResponse;

/**
 * @summary Get a hearing by problem id
 */
export const useGetHearing = <
  TError =
    | ErrorResponse
    | ErrorResponse
    | ErrorResponse
    | ErrorResponse
    | ErrorResponse,
>(
  problemId: string,
  options?: {
    swr?: SWRConfiguration<Awaited<ReturnType<typeof getHearing>>, TError> & {
      swrKey?: Key;
      enabled?: boolean;
    };
  },
) => {
  const { swr: swrOptions } = options ?? {};

  const isEnabled = swrOptions?.enabled !== false && !!problemId;
  const swrKey =
    swrOptions?.swrKey ??
    (() => (isEnabled ? getGetHearingKey(problemId) : null));
  const swrFn = () => getHearing(problemId);

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(
    swrKey,
    swrFn,
    swrOptions,
  );

  return {
    swrKey,
    ...query,
  };
};
