/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * AI-Consultant Admin API
 * AI-Consultant Admin API
 * OpenAPI spec version: 1.0.0
 */

import type { Key, SWRConfiguration } from "swr";
import useSwr from "swr";
import { adminApiClient } from "../../client";
import type { ErrorResponse, GetReportSuccessResponse } from ".././model";

/**
 * @summary Get a report by problem id
 */
export const getReport = (problemId: string) => {
  return adminApiClient<GetReportSuccessResponse>({
    url: `/api/reports/${problemId}`,
    method: "GET",
  });
};

export const getGetReportKey = (problemId: string) =>
  [`/api/reports/${problemId}`] as const;

export type GetReportQueryResult = NonNullable<
  Awaited<ReturnType<typeof getReport>>
>;
export type GetReportQueryError =
  | ErrorResponse
  | ErrorResponse
  | ErrorResponse
  | ErrorResponse
  | ErrorResponse;

/**
 * @summary Get a report by problem id
 */
export const useGetReport = <
  TError =
    | ErrorResponse
    | ErrorResponse
    | ErrorResponse
    | ErrorResponse
    | ErrorResponse,
>(
  problemId: string,
  options?: {
    swr?: SWRConfiguration<Awaited<ReturnType<typeof getReport>>, TError> & {
      swrKey?: Key;
      enabled?: boolean;
    };
  },
) => {
  const { swr: swrOptions } = options ?? {};

  const isEnabled = swrOptions?.enabled !== false && !!problemId;
  const swrKey =
    swrOptions?.swrKey ??
    (() => (isEnabled ? getGetReportKey(problemId) : null));
  const swrFn = () => getReport(problemId);

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(
    swrKey,
    swrFn,
    swrOptions,
  );

  return {
    swrKey,
    ...query,
  };
};
