// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"context"
	"github.com/goda6565/ai-consultant/backend/internal/domain/document/service"
	"github.com/goda6565/ai-consultant/backend/internal/infrastructure/environment"
	"github.com/goda6565/ai-consultant/backend/internal/infrastructure/google/database"
	"github.com/goda6565/ai-consultant/backend/internal/infrastructure/google/database/repository/chunk"
	"github.com/goda6565/ai-consultant/backend/internal/infrastructure/google/database/repository/document"
	"github.com/goda6565/ai-consultant/backend/internal/infrastructure/google/storage"
	"github.com/goda6565/ai-consultant/backend/internal/infrastructure/http/echo"
	"github.com/goda6565/ai-consultant/backend/internal/infrastructure/http/echo/admin"
	"github.com/goda6565/ai-consultant/backend/internal/infrastructure/http/echo/admin/handler"
	document3 "github.com/goda6565/ai-consultant/backend/internal/infrastructure/http/echo/admin/handler/document"
	"github.com/goda6565/ai-consultant/backend/internal/infrastructure/zap"
	document2 "github.com/goda6565/ai-consultant/backend/internal/usecase/document"
)

// Injectors from wire.go:

func InitAdminApplication(ctx context.Context) (*App, func(), error) {
	environmentEnvironment := environment.ProvideEnvironment()
	logger, cleanup := zap.ProvideZapLogger(environmentEnvironment)
	appPool, cleanup2 := database.ProvideAppPool(ctx, environmentEnvironment)
	documentRepository := document.NewDocumentRepository(appPool)
	storagePort := storage.NewClient(ctx)
	duplicateChecker := service.NewDuplicateCheckService(documentRepository)
	createDocumentInputPort := document2.NewCreateDocumentUseCase(environmentEnvironment, documentRepository, storagePort, duplicateChecker)
	createDocumentHandler := document3.NewCreateDocumentHandler(createDocumentInputPort)
	vectorPool, cleanup3 := database.ProvideVectorPool(ctx, environmentEnvironment)
	chunkRepository := chunk.NewChunkRepository(vectorPool)
	deleteDocumentInputPort := document2.NewDeleteDocumentUseCase(documentRepository, chunkRepository)
	deleteDocumentHandler := document3.NewDeleteDocumentHandler(deleteDocumentInputPort)
	getDocumentInputPort := document2.NewGetDocumentUseCase(documentRepository)
	getDocumentHandler := document3.NewGetDocumentHandler(getDocumentInputPort)
	listDocumentInputPort := document2.NewListDocumentUseCase(documentRepository)
	listDocumentHandler := document3.NewListDocumentHandler(listDocumentInputPort)
	strictServerInterface := handler.NewAdminHandlers(createDocumentHandler, deleteDocumentHandler, getDocumentHandler, listDocumentHandler)
	router := admin.NewAdminRouter(strictServerInterface, environmentEnvironment)
	server := echo.NewBaseServer(environmentEnvironment, logger, router)
	app := &App{
		Server: server,
	}
	return app, func() {
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}
