name: "Frontend CI"

on:
  push:
    paths:
      - "frontend/**"
      - ".github/workflows/ci-frontend.yaml"

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Biome
        uses: biomejs/setup-biome@v2
        with:
          version: 2.2.0
      - name: Run Biome
        run: biome ci src/